USE [master]
GO

/****** Object:  Database [DBPN]    Script Date: 03/11/2018 21:15:08 ******/
CREATE DATABASE [DBPN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBPN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DBPN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBPN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DBPN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DBPN] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBPN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBPN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBPN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBPN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBPN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBPN] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBPN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBPN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBPN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBPN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBPN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBPN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBPN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBPN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBPN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBPN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBPN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBPN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBPN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBPN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBPN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBPN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBPN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBPN] SET RECOVERY FULL 
GO

ALTER DATABASE [DBPN] SET  MULTI_USER 
GO

ALTER DATABASE [DBPN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBPN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBPN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBPN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBPN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBPN] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBPN] SET  READ_WRITE 
GO

